### PR TITLE
(ready): Allow "<" ">" "|" in fantasy name pattern

### PR DESCRIPTION
**Pull request by iology**
ping #399

### CODE REVIEW

**Comment by AquariusPower** [comment]
interesting documentation.
I use a lot the "valid chars" 0x20 to 0x7E

**Comment by iology** [comment]
Doc/Obsolete/Bugs.txt
178://(hs) Choosing a name including one of characters '?', '*', '|', '<' or '>' and saving will crash (at least in Windows).

Do these keys still crash the game now?

**Comment by iology** [comment]
The special symbols are not allowed in filename. The save files should use safer names.

**Comment by iology** [comment]
This PR is ready now.

**Pull request merged**
