### PR TITLE
Warn about spoiling food when consuming them

### PR DESCRIPTION
**Pull request by iology**
Also make ActivateInDNDMode() not called by actions themselves. This makes it easier to maintain the logic.

ping #463

### CODE REVIEW

**Comment by AquariusPower** [comment]
interesting, I googled, DND is "do not disturb" and is quite generic.
may be the variables could be named alike but specifically as:
SpoilingDND
GulpingDND
NibblingDND

**Comment by iology** [comment]
Nibbling is only related to where the food was at the beginning. So there are public functions for other game mechanics.

Spoiling and Gulping are for dangers that arise from the current action.

InDNDMode(), after this patch, is only for external conditions.

The names could be changed to IgnoreSpoiled, IgnoreBloated and what? I can't think of a good name for DNDMode. :p

**Comment by AquariusPower** [comment]
not a requirement at all!
what really matters is the logic that provides us missing/improved functionalities, 
these (questionable) "better" naming are unnecessary.

I keep changing naming of functions and vars (mainly the ones I create) quite often to make them more clear to me, this doesnt mean it will be as clear to other ppl and they may further change'm in the future xD

**Comment by iology** [comment]
I thought about unifying internal and external conditions with `std::map<cchar, bool> flags`.

**Comment by AquariusPower** [comment]
I think the point is how long they will be available/required.
as soon an action ends, if the user opted for DND at that time, makes sense anymore as later he may be in other kinds of danger and need that question again.
unless I am missing something? :)

**Comment by iology** [comment]
Yep, I'm not sure how long the DND mode should last for external threats (mainly Kamikazedwarves and named monsters). Maybe extreme dangerous monsters should always be warned (only when resting in place).

**Comment by AquariusPower** [comment]
I added, for the k.dwarvs, a sfx laugh sound in one of the PRs, but still it should be an interruption (despite I think it already is). Btw I try to always keep important burnable/xplodable things on chests.

**Pull request merged**
