### PR TITLE
Fix fantasy name pattern input

### PR DESCRIPTION
**Pull request by AquariusPower**
https://github.com/Attnam/ivan/issues/399

### CODE REVIEW

**Comment by AquariusPower** [comment]
ugh... felib shouldnt know about anything outside it...
the parameter named fantasyname makes no sense...

**Comment by iology** [comment]
Yeah, ugly code. I suspect the old mysterious logic is related to the bugs before I change IsAcceptableForStringQuestion(**char*) to IsAcceptableForStringQuestion(**int**).

**Comment by iology** [comment]
Not related to missing font glyphs too. Checked all call sites but found nothing special. I think that restriction can be safely removed.

**Comment by iology** [comment]
Oh, I haven't checked the config file: `inputfile::ReadWord()` in FeLib/Source/save.cpp

Definitely have problem with `stringoption::SaveValue()`.

**Comment by AquariusPower** [comment]
'<<' and '|' are present in defines.dat, could be related I guess.

`stringoption::SaveValue`
`SaveFile << '\"' << Value.CStr() << '\"';`

mmm... may be we could just remove the restriction and make tests see if anything breaks.

if you find a better way, feel free to propose another PR :)

I usually put these things as optional (like that behavior simple modifier) to skip the research and tests step btw :)

**Comment by AquariusPower** [comment]
closed in favor of #405, 
I can re-open if needed :)

**Pull request closed without merging**
