### PR TITLE
IVAN music system 1.0

### PR DESCRIPTION
**Pull request by fejoa**
Plays music files in midi format at certain points in the game. The mood of the music changes depending on your hit points. This can be expanded later, to include other metrics like danger level, town hostility etc.

There are three midi files containing music at the moment. These play:
1) While playing in either underwater tunnels or Gloomy caves
2) While sumo wrestling
3) While in Attnam town

There are spaces for more music files, which have not been prepared yet, but will be forthcoming in the coming months. These are:
1) defeat.mid
2) mainmenu.mid
3) newgame.mid
4) victory.mid
5) world.mid
6) And on any level in the dungeon script - you can choose where.

### CODE REVIEW

**Comment by fejoa** [comment]
@emlai : Can you please check the https://github.com/Attnam/ivan/tree/IVANMusic branch for compilability in LINUX? 
You will probably need:
pthread library
rtmidi library
maybe check out compiling for https://www.music.mcgill.ca/~gary/rtmidi/index.html#compiling

**Comment by emlai** [comment]
On Mac this crashes with the following stack trace when launched:

```
Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000068

Thread 1 Crashed:: AudioThread
0   libsystem_c.dylib             	0x00007fff9302e09e flockfile + 4
1   libsystem_c.dylib             	0x00007fff930305d9 fseek + 55
2   ivan                          	0x000000010bf24539 _MIDI_readbuf + 41
3   ivan                          	0x000000010bf242e6 MPB_ResetMIDITracks + 54
4   ivan                          	0x000000010bf2424f MPB_PlayMIDIFile + 79
5   ivan                          	0x000000010bf1ef34 audio::PlayMIDIFile(char*, int) + 244
6   ivan                          	0x000000010bf1e575 audio::Loop(void*) + 405
7   libSDL2-2.0.0.dylib           	0x000000010c2fceae SDL_RunThread + 60
```

and `MidiOutDummy: This class provides no functionality.` is printed to the console.

I'll try to test this on a Linux computer at the university tomorrow. Not sure if I can install arbitrary software there though.

**Comment by emlai** [comment]
I made some changes to make this build and install properly with the Autotools build system: #160

**Comment by emlai** [comment]
Hmm, I managed to set the preprocessor definitions and link the dependencies for RtMidi as described in https://www.music.mcgill.ca/%7Egary/rtmidi/index.html#compiling, and now the `MidiOutDummy` message is gone but it still crashes at the same spot.

**Comment by emlai** [comment]
Ah, the crash was caused by `GetMusicDir()` returning the wrong directory on Unix. Added a commit to #160 to fix that.

**Comment by emlai** [comment]
Finally, it compiles and runs, but there's no sound and the "Select MIDI output device" setting shows "No output Device" [sic].

**Comment by fejoa** [comment]
Thanks so much for checking this out. Sorry, I created the GetMusicDir() bug :\
@AdrianGin : Can you recommend a nice midi output device to install to Linux?

**Comment by AdrianGin** [comment]
@fejoa, @emlai Fluidsynth is good. Or Timidity. I tested it on Linux with fluidsynth.
http://www.fluidsynth.org/

**Comment by AdrianGin** [comment]
@fejoa , @emlai , also recommend using the Yamaha XG Soundfont, http://www.ronimusic.com/sf2/Yamaha_XG_Sound_Set.sf2

On windows I use the CoolSoft VirtualMIDISynth instead of the Windows GS Wavetable Synth as it will sound better with the Yamaha XG Soundfont.

**Comment by fejoa** [comment]
@emlai : Does it perform in a satisfactory way on inlux and Mac? Can it be merged?

**Comment by emlai** [comment]
Sorry, I've been sick the last couple of days so I haven't looked at this.

I got it working now on Mac with fluidsynth, and it works acceptably, but there's no music in the main menu or in the world map. Also, I don't know if this has anything to do with it, but fluidsynth says: `warning: Instrument not found on channel 9 [bank=128 prog=35], substituted [bank=128 prog=0]`.

**Comment by fejoa** [comment]
@emlai I'm sorry to hear you were ill. I hope you are feeling better. Thanks for checking that this works. I'll merge it in to master later this week.

**Pull request merged**
