### PR TITLE
Travis continuous integration

### PR DESCRIPTION
**Pull request by emlai**
This adds automated builds using [Travis](https://travis-ci.org). The builds are done on all pushes and pull requests. Travis will test that the code compiles with all 8 combinations of Linux/Mac,  clang/gcc, and wizard mode on/off.

Admin rights are required to enable Travis CI for this repository. Just login to Travis and go to https://travis-ci.org/profile/Attnam and flick the switch.

### CODE REVIEW

**Comment by andrewtweber** [comment]
😮  yes! I added the badge to `README.md` as well.

**Comment by emlai** [comment]
Ah yes, I meant to to do that but somehowforgot. Awesome!

**Comment by andrewtweber** [comment]
@emlai paging you for help

The latest Travis builds are failing and it seems like there's 2 reasons:
- unable to connect to certain repositories
- missing a couple of dependencies: libegl1-mesa-dev and libgles2-mesa-dev

https://travis-ci.org/Attnam/ivan/builds/285394940

Any chance you could help us fix these? :) Thanks!

**Comment by emlai** [comment]
@andrewtweber  Sure: #271 :)

**Pull request merged**
