### PR TITLE
(ready) Go thru route (mini-map) and re-apply previous

### PR DESCRIPTION
**Pull request by AquariusPower**
- added 'route' to go 'g' funcionality using the mini-map look mode to select any far tortuous path target/destination

- apply 'A' now re-apply previous item

made some basic tests and fixed all crashes, seems good now.

### CODE REVIEW

**Comment by fejoa** [comment]
From some cursory testing, so far on Windows, when I pull up the map and press "l" for look mode, I get a crash.

**Comment by fejoa** [comment]
In the item menu, if I press "F1", I get a crash.

**Comment by AquariusPower** [comment]
I will test both thx!

**Comment by AquariusPower** [comment]
I am not being able to simulate these crashes.
could you drop **your config file contents**? the crash may be due to some interaction with other options I guess.

Obs.: the item menu 'i' has a useless F1 behavior of showing info about the first item, but should not crash at all (and doesnt here)

**Comment by fejoa** [comment]
My config was just default plus the dungeon scale x2.

Might be Windows specific. I can try your config file within 48 hours. 

I can't really identify all the other bugs, so when we merge and generate the next build we will leave it to others to test for bugs. If it's serious, we will find out soon :)

**Comment by AquariusPower** [comment]
F1 seems to not be working at all with default config (I deleted the file and let the game create a new one), I will try to understand what is happening.

Btw, the default config also now has the resolution as 640x480, but should be 800x600 as vanilla...
anyway in both cases, it didnt show the map at all on my first run (dont know why), but it is showing now, and still w/o crashes in mapLookMode.

obs.: due to the huge amount of new features, I suggest name it alpha release :>

and if someone manage to test/implement this for windows, would help a huge lot! https://github.com/Attnam/ivan/issues/386

**Comment by AquariusPower** [comment]
now I think that may be you got a special/unique/rare condition, and that map look crash may only happen on your savegame (randomly in new game too), so I wonder if you could upload your savegame files? if possible in .7z.zip (github doesnt accept just .7z) so I spend just a little of my 100MB/day connection xD

**Comment by fejoa** [comment]
[Here's an example](https://github.com/Attnam/ivan/files/2409177/Save.7z.zip). This is as small as I could get it :D

**Comment by fejoa** [comment]
Teleporting the player instead of Jenny, works well but it is possibly slow for some reason? Not urgent for not.

**Comment by AquariusPower** [comment]
in my save, in wizard mode, I moved to UT1, WorldMap and then over vesana, 3 time, and all were instantaneous,
I will wizard your save and try again :)

**Comment by AquariusPower** [comment]
your save is special!
in the ContinueMenu to show the saves list, during your save file, while reading it's info, it created a huge memory leak here
during the SkipGameScript() call, at 
```
void gamescript::Load(inputfile& SaveFile)
{
  script::Load(SaveFile);
  SaveFile >> Team >> Dungeon;
```
while loading the Team data :o

w/o your save on the list: resident 135mb, virtual 393mb
with it: 274mb 2131mb!

here the stack. I dont know if it may help if someone reads this, I am not used to memory leaks, allocator, malloc etc, so if someone have any idea?
```
#0  _int_malloc(av = 0x7ffff6618b20 <main_arena>, av@entry = 0x7ffff6618b20 <main_arena>, bytes = 72, bytes@entry = 72) at malloc.c:3802
#1  __GI___libc_malloc(bytes = 72) at malloc.c:2913
#2  operator new(unsigned long)() at :0
#3  __gnu_cxx::new_allocator<std::_List_node<std::pair<int, teamscript> > >::allocate(this = 0x7ffffffc5490, __n = 1) at /usr/include/c++/5/ext/new_allocator.h:104
#4  std::__cxx11::_List_base<std::pair<int, teamscript>, std::allocator<std::pair<int, teamscript> > >::_M_get_node(this = 0x7ffffffc5490) at /usr/include/c++/5/bits/stl_list.h:392
#5  std::__cxx11::list<std::pair<int, teamscript>, std::allocator<std::pair<int, teamscript> > >::_M_create_node<std::pair<int, teamscript> const&>(this = 0x7ffffffc5490) at /usr/include/c++/5/bits/stl_list.h:571
#6  std::__cxx11::list<std::pair<int, teamscript>, std::allocator<std::pair<int, teamscript> > >::_M_insert<std::pair<int, teamscript> const&>(this = 0x7ffffffc5490, __position = ) at /usr/include/c++/5/bits/stl_list.h:1763
#7  std::__cxx11::list<std::pair<int, teamscript>, std::allocator<std::pair<int, teamscript> > >::push_back(this = 0x7ffffffc5490, __x = ) at /usr/include/c++/5/bits/stl_list.h:1089
#8  std::__cxx11::list<std::pair<int, teamscript>, std::allocator<std::pair<int, teamscript> > >::_M_fill_initialize(this = 0x7ffffffc5490, __n = 8567009676, __x = ) at /usr/include/c++/5/bits/stl_list.h:1704
#9  std::__cxx11::list<std::pair<int, teamscript>, std::allocator<std::pair<int, teamscript> > >::list(this = 0x7ffffffc5490, __n = 8589934605, __value = , __a = ) at /usr/include/c++/5/bits/stl_list.h:631
#10  std::__cxx11::list<std::pair<int, teamscript>, std::allocator<std::pair<int, teamscript> > >::insert(this = 0xfc8318, __position = , __n = 8589934605, __x = ) at /usr/include/c++/5/bits/list.tcc:120
#11  std::__cxx11::list<std::pair<int, teamscript>, std::allocator<std::pair<int, teamscript> > >::resize(this = 0xfc8318, __new_size = 8589934605, __x = ) at /usr/include/c++/5/bits/list.tcc:207
#12  operator>><std::pair<int, teamscript> >(SaveFile = , List = ) at FeLib/Include/save.h:326
#13  gamescript::Load(this = 0xfc8310, SaveFile = ) at Main/Source/script.cpp:1221
#14  operator>>(SaveFile = , Script = @0x7ffffffc5670: 0xfc8310) at Main/Source/script.cpp:1233
#15  SkipGameScript(pSaveFile = 0x7ffffffc5db0) at Main/Source/main.cpp:58
#16  iosystem::ContinueMenu(TopicColor = 65535, ListColor = 38066, DirectoryName = , iSaveFileVersion = 133, bAllowImportOldSavegame = true) at FeLib/Source/feio.cpp:1114
#17  main(argc = 1, argv = 0x7ffffffc62a8) at Main/Source/main.cpp:152
```
the file version is correct, 133,
so my guess is it could be other branch than my fully merged one, if so, which one you compiled?

also, this line at feio.cpp ContinueMenu() 
`skipSeek(&SaveFile);` (actually SkipGameScript())
could be removed if we re-arranged the saved data order  by moving the game script after what is required during the games listing better info like "dungeon and wizard mode", but that would make importing old saves impossible despite I guess it is not that crucial.

**Comment by AquariusPower** [comment]
jus for this test (already reverted) I commented these lines in feio.cpp
```
//      skipSeek(&SaveFile); //DUMMY (for here) binary data skipper
//      SaveFile >> rfi.CurrentDungeonIndex >> rfi.CurrentLevelIndex; DBG2(rfi.CurrentDungeonIndex,rfi.CurrentLevelIndex);
//      SaveFile >> rfi.Camera; //skipper
//      SaveFile >> rfi.WizardMode;
```
but I knew the problem would happen again during load, despite showing on the list now, was just to be sure.
so in short, I am unable to load that game :(

**Pull request merged**
