### PR TITLE
Ring of unchanging prevents polymorphing

### PR DESCRIPTION
**Pull request by AlexMooney**
Also prevents changing back to normal

### CODE REVIEW

**Comment by emlai** [comment]
Was this discussed somewhere? This kind of duplicates the behavior of the polycontrol ring, since that can be used to prevent polymorphing too.

**Comment by AlexMooney** [comment]
It's discussed [here](https://attnam.com/topics/polymorph-victory), and a similar item is mentioned [in the dev notes](https://github.com/Attnam/ivan/blob/df6b70cbead8f5b9ecd1fe7a8f772c31c37069c5/Doc/Obsolete/Item%20ideas%20II.txt#L28).  This item is different from polycontrol in that it completely prevents polymorph and changing back from polymorph.  Think of it as a more convenient alternative, although it may be very unbalanced because you can uncontrolled polymorph into something powerful and then put the ring on.

**Comment by serin-delaunay** [comment]
I think it should have a higher teleport priority. Teleporting away the ring of unchanging while the player is polymorphed into something powerful could really ruin someone's day. :D

**Comment by AlexMooney** [comment]
@serin-delaunay I set it to 1000, like the other high-value rings.  Strangely, the amulets don't have `TeleportPriority` values!  You'd think all of them represent a significant target for the enemies.

**Comment by serin-delaunay** [comment]
Yeah, the life saving and resistance amulets probably merit a high TeleportPriority too. Not so sure about the ESP amulet.
Aren't non-pet NPC's amulets invisible to the player when looking at them? If amulets are "hidden" I wonder how much sense it makes for them to be targets of item teleportation when equipped.

**Comment by fejoa** [comment]
@AlexMooney is this ready as well?

**Comment by AlexMooney** [comment]
I recall a discussion on the board that ended up with people not liking
this ring. I think we were going to make it only generate as a  scabies
champion item. I'm also inclined to shorten the amount of time it gives you
in lock after the ring comes off.

**Comment by AlexMooney** [comment]
This was effectively merged in https://github.com/Attnam/ivan/pull/272.  Closing.

**Pull request closed without merging**
