### PR TITLE
lgtm fixes

### PR DESCRIPTION
**Pull request by fejoa**

### CODE REVIEW

**Comment by AquariusPower** [comment]
now I get why I am getting most of the lgtm messages at https://github.com/Attnam/ivan/pull/587

I copied these changes at that branch, created a new macro (with 15 params), 
but whenever  I try to merge your branch with mine, it keeps aiming at an older repository commit of my branch... I dont get it...
https://github.com/AquariusPower/ivan/compare/SomeFixes1234...fejoa:lgtm-fixes

**Comment by fejoa** [comment]
> but whenever I try to merge your branch with mine, it keeps aiming at an older repository commit of my branch... I dont get it...

I don't get it either. Oh well, it's not very much code to copy over. Funny how the compiler complained about this commit when the wizard mode flag was set... I must have overlooked something. Anyway, the code you put into #587 seems to have done the job :)

**Comment by fejoa** [comment]
Oh! Wait it's this line here: https://github.com/Attnam/ivan/pull/589/files#diff-28236a94b2b7ad44dd69f1be93655df6R324
For which you added `DEVCMDMSG15` lol!

**Comment by AquariusPower** [comment]
> Oh! Wait it's this line here: https://github.com/Attnam/ivan/pull/589/files#diff-28236a94b2b7ad44dd69f1be93655df6R324
> For which you added `DEVCMDMSG15` lol!

I am not sure, but it could be something new I coded here :>
https://github.com/Attnam/ivan/blob/ed7f7ab114bf9b8f5be5e910bef3d9bcd4eb81ad/Main/Source/devcons.cpp#L184
I thought DEVCMDMSG11? no.... 15 and put dummies on it's call xD

**Comment by fejoa** [comment]
Great. I guess we can Close #589

**Pull request closed without merging**
