### PR TITLE
Further restrict the range of craftable items

### PR DESCRIPTION
**Pull request by iology**
esp. prevent making a magical item made of plant fiber

### CODE REVIEW

**Comment by AquariusPower** [comment]
and also made of anything else,
wish I knew that b4 creating `cmdcraftfilters.cpp` and related script `prepareCraftFilters.sh`, wonder if they are still useful? :>

to see almost a full list of what will be further denied (this is not the best filter tho)
`egrep "PostFix = \"[^\"]|Possibility = 0| Config |^[^ {}]" item.dat`

**Comment by iology** [comment]
You can get a lot of "plant fiber stones" in UT1, then make a lot of belt of levitation and fly across the ocean.

I also blacklisted the categories: POTION, SCROLL, MISC.

A better approach could be to add the property "canBeCrafted" in Script/item.dat . The property can be inherited from the base class. This can be done after the planned release in this month (but I'm not sure if that will spoil my fun ;).

**Comment by iology** [comment]
Or a property "CraftDifficulty": 0 - impossible to craft, 1 - easiest, 2,3,...,N - harder

**Comment by red-kangaroo** [comment]
I like CraftDiffifulty. All magic items should be uncraftable anyway.

**Comment by AquariusPower** [comment]
at `cmdcraft.cpp` there is `applyDifficulty()` with some stuff already configured (hard coded) there, I think such database field could fit directly there at `recipedata.fDifficulty`.

**The fumble formula:**
it is a per turn check for fumble, imagine like each hammer/carvingTool strike, may break the thing,
crafthandle::CheckFumble() calls craftcore::CheckFumble()
Crafting should not be something very difficult.
As initial stats are all around 10, to require some progress to become a "novice crafter", it would require to have all stats around 20 (there is another formula for each stat weight) but I am not sure that is a good value, could be more than 20 I guess?
Btw.: The minor fumble result (weak explosion) was just a fun/quick/easy way to let something bad happen (fire sparks from meltables at anvil), but makes no sense when carving on a workbench.

**Comment by fejoa** [comment]
This seems like a self-contained change. Can it be merged now?

**Comment by iology** [comment]
Yes!

**Pull request merged**
