### PR TITLE
Make sirens randomly spawned monsters

### PR DESCRIPTION
**Pull request by red-kangaroo**
Sirens are fully implemented in the code, including their special attacks, they only cannot be generated. This fixes that.

I also added several skin colors, because who doesn't like exotic skin colors?

### CODE REVIEW

**Comment by fejoa** [comment]
@red-kangaroo this has got lots of extra file changes. Would you be able to merge your changes in from an up-to-date feature branch? If you get stuck, I can explain how to do this.

**Comment by red-kangaroo** [comment]
@fejoa Definitely! Sorry, I forgot to update the branch. Everything should be up-to-date, fixed and finished now.

**Comment by fejoa** [comment]
Awesome, thanks @red-kangaroo

**Comment by andrewtweber** [comment]
Seems kind of funky having a bunch of colors (red, blue, green), and then a couple ethnicities (Caucasian, Hispanic). I don't think there's any "PC" issues, it's just weird. Also does Hispanic even exist in this world? Maybe Tweraifan would be better

**Comment by andrewtweber** [comment]
I just noticed the Asian ones in there too. If nobody else thinks it's weird then we can keep it I guess

**Comment by fejoa** [comment]
It's weird now you mention it. The config names appear only in the script don't they? Let's change these to neutral config names.

**Comment by red-kangaroo** [comment]
@andrewtweber @fejoa It's kinda weird, but the names only appear in script. Players will only see "siren" for all of them. It's probably just a description for devs, because you can easily imagine what an asian siren would look like. :)

**Comment by andrewtweber** [comment]
Got it. Let's not worry about it then

**Pull request merged**
