### PR TITLE
Limit golem spawns to gloomy caves and tomb of xinroch

### LINKED ISSUE #417: Prevent golems from appearing in Underwater Tunnel
https://attnam.com/posts/29134

### PR DESCRIPTION
**Pull request by fejoa**
Fixes #417

### CODE REVIEW

**Comment by iology** [comment]
Too strict, maybe? Earlier, before that surprise was introduced, I could see dangerous monsters if I stayed in the UT too long. Was this feature also removed in a previous commit?

**Comment by red-kangaroo** [comment]
I like that. Golems should not spawn that early.

@iology You will still see dangerous monsters other than golems.

**Comment by andrewtweber** [comment]
Just to clarify, will they still show up in UT4 (the crystal level?)

**Comment by red-kangaroo** [comment]
@andrewtweber The golems in UT4 and the one guarding the secret chest are pre-defined and will be generated even if we forbid golems from spawning in UT.

**Pull request merged**
